info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  codegen:
    defaultPackage: example
  profile: rest-api
  mime:
    disable:
      accept:
        header:
          userAgents:
          - Gecko
          - WebKit
          - Presto
          - Trident
    types:
      json:
      - application/json
      - text/json
      hal:
      - application/hal+json
      - application/hal+xml
      xml:
      - text/xml
      - application/xml
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      js: text/javascript
      rss: application/rss+xml
      text: text/plain
      all: '*/*'
  views:
    default:
      codec: html
  #tag::mailConfig[]
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    username: ${SMTP_USERNAME:}
    password: ${SMTP_PASSWORD:}
    default:
      from: ${SMTP_FROM:no-reply@example.com}
    props:
      mail.smtp.auth: ${SMTP_AUTH:false}
      mail.smtp.starttls.enable: ${SMTP_STARTTLS:false}
  #end::mailConfig[]
#tag::emailProvider[]
email:
  provider: ${EMAIL_PROVIDER:smtp}
#end::emailProvider[]
#tag::sendgrid[]
sendgrid:
  api: ${SENDGRID_APIKEY:}
  from: ${SENDGRID_FROM_EMAIL:}
#end::sendgrid[]
#tag::awsses[]
aws:
  ses:
    source: ${AWS_SOURCE:}
    region: ${AWS_REGION:}
#end::awsses[]
